//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BJL.SurveyMaker.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestionAnswer
    {
        public System.Guid Id { get; set; }
        public System.Guid QuestionId { get; set; }
        public System.Guid AnswerId { get; set; }
        public bool IsCorrect { get; set; }
    }
}
