//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BJL.SurveyMaker.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestion
    {
        public System.Guid Id { get; set; }
        public string Text { get; set; }
    }
}
